export const Products = [
  { name: "milk" },
  { name: "eggs" },
  { name: "bread" },
  { name: "rice" },
  { name: "noodle" },
  { name: "chicken" },
  { name: "cheese" },
  { name: "beer" },
  { name: "fries" },
  { name: "salad" },
  { name: "watermelon" },
  { name: "tomatoes" },
  { name: "grapes" },
  { name: "broccoli" },
  { name: "carrot" },
  { name: "lemon" },
  { name: "orange" },
  { name: "apple" },
  { name: "strawberry" },
  { name: "cherry" },
];
